(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.shape25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0.573)","rgba(255,255,255,0)"],[0,0.145,1],-14.8,-54.7,0,-14.8,-54.7,73.8).s().p("AiAKmQiIgah2hOQjtifg4kXQg4kYCejtQBOh1B1hMQBvhKCFgbQEXg4DtCfQDuCeA4EYQA4EXifDuQieDtkXA4QhFAOhDAAQhAAAhAgMg");
	this.shape.setTransform(92,136.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(23,67.9,138.1,138);


(lib.shape22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#272425").s().p("AA8BEQgtghgkgkQgVAIgTgLQgbgRgQg7IgugnIAtAdQA/AOAXAZQAQAQgEATQBAAsBeBcQglgNg2gng");
	this.shape.setTransform(15.1,12);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.2,24);


(lib.shape19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#272425").s().p("Ag7ATQDhhxBkggQhVA9jnBlIjYBbg");
	this.shape.setTransform(26.7,12.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,53.3,25.4);


(lib.shape16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#272425").s().p("AgQAJQgEgIADgGQACgIAIgDIAOgBQAHADAEAHQADAHgDAGQgDAIgHAEIgNAAQgIgDgDgGg");
	this.shape.setTransform(2,71.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#272425").ss(0.5,0,0,4).p("AAEFkIgHrH");
	this.shape_1.setTransform(1.5,35.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1,3.9,74);


(lib.shape15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 93
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#404041").ss(0.8,0,0,4).p("AAAAfIAAg9");
	this.shape.setTransform(97,16.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#272425").ss(0.8,0,0,4).p("AAAAeIAAg7");
	this.shape_1.setTransform(98.5,16.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#F0F0F1").ss(0.8,0,0,4).p("AAAAfIAAg9");
	this.shape_2.setTransform(97.3,16.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(0.8,0,0,4).p("AhXAiIAAgwIAAgFIAAgKABYAcIAAg8");
	this.shape_3.setTransform(90,16.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#818285").ss(0.8,0,0,4).p("AAAAgIAAgwIAAgGIAAgJ");
	this.shape_4.setTransform(81.6,16.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#8B8C8F").ss(0.8,0,0,4).p("AAAAfIAAgwIAAgJIAAgF");
	this.shape_5.setTransform(83.2,16.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#E8E8E9").ss(0.8,0,0,4).p("AAAgfIAAAFIAAAJIAAAw");
	this.shape_6.setTransform(82.8,16.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#D4D5D7").ss(0.8,0,0,4).p("AAAgfIAAAEIAAAKIAAAx");
	this.shape_7.setTransform(84.4,16.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#C1C2C4").ss(0.8,0,0,4).p("AAAggIAAADIAAAKIAAA0");
	this.shape_8.setTransform(86,16.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#959799").ss(0.8,0,0,4).p("AAAgfIAAAEIAAAKIAAAw");
	this.shape_9.setTransform(84.7,16.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#AEAFB1").ss(0.8,0,0,4).p("AAAgfIAAADIAAAJIAAA0");
	this.shape_10.setTransform(87.6,16.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#ABACAF").ss(0.8,0,0,4).p("AAAAgIAAg0IAAgIIAAgE");
	this.shape_11.setTransform(87.9,16.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#A0A1A4").ss(0.8,0,0,4).p("AAAAgIAAgyIAAgJIAAgE");
	this.shape_12.setTransform(86.3,16.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#8A8B8E").ss(0.8,0,0,4).p("AAAAgIAAg0IAAgGIAAgF");
	this.shape_13.setTransform(90.7,16.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#9B9D9F").ss(0.8,0,0,4).p("AAAgfIAAAEIAAAHIAAA0");
	this.shape_14.setTransform(89.1,16.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#C2C3C5").ss(0.8,0,0,4).p("AAAAgIAAg0IAAgGIAAgF");
	this.shape_15.setTransform(91,16.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#B6B7BA").ss(0.8,0,0,4).p("AAAgfIAAAEIAAAIIAAAz");
	this.shape_16.setTransform(89.4,16.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#D9D9DB").ss(0.8,0,0,4).p("AAAAfIAAgzIAAgDIAAgI");
	this.shape_17.setTransform(94.1,16.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#E4E5E6").ss(0.8,0,0,4).p("AAAgeIAAAJIAAABIAAAz");
	this.shape_18.setTransform(95.7,16.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#555557").ss(0.8,0,0,4).p("AAAAfIAAg0IAAgBIAAgI");
	this.shape_19.setTransform(95.4,16.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#68686B").ss(0.8,0,0,4).p("AAAgeIAAAHIAAADIAAAz");
	this.shape_20.setTransform(93.8,16.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#CDCED0").ss(0.8,0,0,4).p("AAAgfIAAAHIAAAEIAAA0");
	this.shape_21.setTransform(92.6,16.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#797A7D").ss(0.8,0,0,4).p("AAAAfIAAgzIAAgFIAAgG");
	this.shape_22.setTransform(92.3,16.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.rf(["#D9DADB","#DBDCDD","#E2E3E4","#EFEFF0","#FFFFFF"],[0.388,0.631,0.784,0.914,1],-6.8,60.2,0,-6.8,60.2,70.1).s().p("AiVASIkAgQIMrgUQgxAJg0AHIgvAEQh2ANiBADIhDABIhdgBg");
	this.shape_23.setTransform(103.1,262.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#D9DADB","#D7D8DA","#D2D3D4","#C8C9CB","#BABBBD","#A8A9AC","#96989A","#DFE0E1","#C5C6C8","#96989A"],[0,0.224,0.306,0.361,0.408,0.447,0.478,0.878,0.925,1],0,-1.3,0.1,1.1).s().p("AjPAeIAAgBIgCgDIgBgFIgCgHQAAgGABgFIACgFQAEgHAFAAIGOgaQAFAAAFAGQAEAHAAAJIAAAHQAAAFgCAEQgDAEgDACIgDABIhcAGIABgDIgDgmIgCgDQAAAAgBAAQAAAAAAABQAAAAAAABQAAAAAAABIACAmIACADIjiAPIAAgBIABgCIgCgmQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIADAmIABACIABABIhPAFIgBAAQgEAAgFgGg");
	this.shape_24.setTransform(93.1,224);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.rf(["#D9DADB","#D7D8D9","#D0D1D2","#C3C4C7","#B2B3B6","#9D9EA1","#8B8C8F"],[0.388,0.573,0.686,0.78,0.867,0.945,1],-9,118.1,0,-9,118.1,143.3).s().p("ApeB2QjIgigqgvQgLgNAAgNQgBg/D8gxIAsgIQDBghD5gJQA2ACA3gFIAMAAQC4gDCdALQCSAJB5AUQDyApALA8IAAAGQABA/j7AxQj7AxllAFIhDAAQk5AAjkgmg");
	this.shape_25.setTransform(99.8,244.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#D9DADB","#BFC0C2","#96989A","#A2A4A6","#C3C4C6","#D8D9DA","#DFE0E1"],[0,0.149,0.4,0.478,0.71,0.89,1],-9.4,0.1,9,0).s().p("AhRAeIgFgGQgDgGgBgIIAAgRQAAgLAIgIQAGgGAIgCIAFgBIB9gCIAEAAQAJABAHAHQAIAIAAALIABARQAAAJgFAHIgDAEQgIAIgMAAIh8ADQgMAAgIgIgAgtAcIAxADQBFACAIgKIAAgCgAhLgPICDgHIg3gDIgWAAQg0AAgCAKg");
	this.shape_26.setTransform(90.7,43.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#D9DADB","#BFC0C2","#96989A","#A2A4A6","#C3C4C6","#D8D9DA","#DFE0E1"],[0,0.149,0.4,0.478,0.71,0.89,1],-9.4,-0.2,9,-0.3).s().p("AhRAbQgIgIgBgLIAAgRQAAgMAIgIIADgDICdgCIAEACQAIAIABAMIAAARQAAALgIAIQgGAHgJABIgEAAIh8ACIgGABQgJgBgGgHgAgoAZIAsADQBKADAEgNgAhLgRICDgHIg3gDIgWgBQgzAAgDALg");
	this.shape_27.setTransform(90.5,36.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#D9DADB","#BFC0C2","#96989A","#A2A4A6","#C3C4C6","#D8D9DA","#DFE0E1"],[0,0.149,0.4,0.478,0.71,0.89,1],-11,0.1,10.6,0).s().p("AhfAjQgEgEgCgFQgDgGgBgIIAAgUQgBgNAKgKQAJgKAOAAICSgCQAOgBAJAKQAKAJAAAOIABAUQAAAHgDAGQgCAFgEAFQgKAJgNABIiTACIgBAAQgNAAgJgJgAgDAeIgDAAIgMABIgDAAIgQABIgNABIA3ADQBXADADgPIgFABIABg8IgBA8IgDAAIAAg8IAAA8IgMAAIAAg8IAAA8IgDABIAAg9IAAA9IgNAAIAAgzIAAAzIgDABIAAg0IAAA0IgNAAIABgzIgBAzIgDAAIAAgzIAAAzIgMABIAAg0IAAA0IgDAAIAAgzIAAAzIgNABIgDAAgAglAgIAAg0gAgVAfIAAg0gAgSAfIAAg0gAhUAfIAAgwgAgGAeIAAg0gAg1AeIAAgxgAhFAeIABgwgAhRAeIAAgwgAgDAeIABg0gAhBAeIAAgwgAAMAdIAAg0IANAAIADgBIAMAAIAEAAIAMgBIADAAIAGgBIgGAAIAAgJIAAAJIgDAAIAAgIIAAAIIgMgBIAAgIIAAAIIgEAAIAAgHIAAAHIgMgBIAAgGIAAAGIgDAAIAAgGIAAAGIgNAAIgDgBIAAgEIAAAEIgIAAIgDAAIAAgFIAAAFIgEAAIAAgEIAAAEIgMAAIAAgEIAAAEIgDAAIAAgEIAAAEIgNAAIAAgEIAAAEIgDAAIAAgDIAAADIgNAAIAAgEIAAAEIgDABIAAgEIAAAEIgMABIAAgFIAAAFIgDAAIAAgFIAAAFIgNAEIAAgJIAAAJIgDABIAAgKIAAAKQgEACAAADIAEAAIADgBIANAAIADAAIAMgBIADAAIANgBIADAAIANgBIADAAIAMgBIAEAAIALgBIADAAgAAJAdIAAg0gAgiAdIAAgxgAgyAdIAAgwgAAMgcIAAgGgABaAZgAhUgWgAAMgXgAhRgXgAgSgdgAgVgdgAgigdg");
	this.shape_28.setTransform(89.8,16.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.rf(["#D9DADB","#D7D8DA","#D2D3D4","#C8C9CB","#BABBBD","#A8A9AC","#96989A","#DFE0E1","#C5C6C8","#96989A"],[0,0.224,0.306,0.361,0.408,0.447,0.478,0.878,0.925,1],0.3,1.1,0,0.3,1.1,28.6).s().p("AjQB/QhVgqgBhBQgChABRgvQBTgwB+gDQB+gEBXArQBXAqACBAQACBAhUAvQgSAKgSAIIAAgEIAAgHQBPgdAXg0Qg/AmgoAVIAAgGQAAgSgLgNQA0gZgBggQgBghg+gWQhAgXheACQhjADg6AXQg8AYABAnQABAhA3AVQgIANABAPIABAiIABAJQgVgHgSgJgAhYh8QiSAbggBJQBig7AsgTQBPghBegDIgEAAQhAAAhFAOg");
	this.shape_29.setTransform(89.4,14.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#D9DADB","#D7D8DA","#D2D3D4","#C8C9CB","#BABBBD","#A8A9AC","#96989A","#DFE0E1","#C5C6C8","#96989A"],[0,0.224,0.306,0.361,0.408,0.447,0.478,0.878,0.925,1],-0.1,-6.1,0.1,6.2).s().p("AidA6QgMgMgDgRIgBgJIgBghQAAgPAHgMQADgGAFgFQAQgQAWAAIAVgBQACAFAEAFQAKAJANAAICTgDQANgBAKgJQAEgFACgFIAPAAQAWAAAQAPIAFAGQALAOAAASIAAAGIABAUIAAAHIAAAEQgBATgOAPQgQAQgWABIgkABIidACIgwABIgBAAQgVAAgQgPgACbABQgJAWgTAGIj3AfICKABQCLgCADgXQADgXgBgRIgCgPgAgHgxQiLACgEAXQgFAkAGATQAAgKAFgMQAJgUATgGQAegKDYgUQgwgDgxAAIgoABg");
	this.shape_30.setTransform(89.7,26.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.rf(["#DBDCDD","#DADADC","#D4D5D6","#CACBCD","#BCBDBF","#AAABAE","#96989A","#D5D6D7","#BABBBE","#96989A"],[0,0.224,0.302,0.361,0.408,0.447,0.478,0.878,0.933,1],0,0,0,0,0,79).s().p("AhdMRIAwADICngLQCOgXBxg8IgKAGQiIBHiaAPQgoAEgnAAQguAAgtgFgAjgL2QiZguh8hmQh8hmhKiNQhHiJgPiaQgPiZAriTQAuiZBmh8QBmh8CNhKQCJhICagPQCYgPCUAsQCZAuB8BmQB8BmBKCNQBICIAPCaQAPCZgsCUQgtCZhnB8Qg2BBhAAzQAhgcAeggQidCJkQA6QiCAchlACQg8gIg7gRgAhCqzQiJANhwA7IjGCZIgOAPIgJAKQiZC6gFDoQgBArAEAvQAJBdAeBSQA9CrCWB8QDfC3EdgcQCHgNBxg3IDJidIAPgSIAGgHQC3jfgckeQgckejei3QhthaiHgoQhhgchkAAQghAAgiADgAmdqHQC4hiEUAFQCLACBmAWQhfgkiIgKQgigDggAAQjlAAivB2g");
	this.shape_31.setTransform(91.1,136.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.rf(["#D9DADB","#D7D8DA","#D2D3D4","#C8C9CB","#BABBBD","#A8A9AC","#96989A","#DFE0E1","#C5C6C8","#96989A"],[0,0.224,0.306,0.361,0.408,0.447,0.478,0.878,0.925,1],0.6,2.3,0,0.6,2.3,86.4).s().p("AkANpQixg0iPh2QiniJhXjEQhUi9AFjQQgEBJAGBGIgBgJQgRixAyirQA1iwB2iQQB2iPCjhWQCehTCygRIABAAIAFAHQAIAHAMABIB8gDQAMAAAIgIIADgEQBYAIBWAaQCxA0CPB2QCQB2BVCjQBTCeARCyQAKBogNBnQgPBhgkBdQg1CIhdByQhABOhOA+Ig1AmIhAAnQgcAPgcAOIhmAoIgxAQIgHABIAAgHQAAgJgEgGQgFgHgFABImOAZQgFAAgEAIIgCAFQgigIgjgKgAhZMfQBUAJBWgIQCagPCIhIIAKgFIARgJIAtgbIA1goQBAgzA2hCQBnh8AtiYQAsiUgPiZQgPiahIiIQhKiOh8hlQh8hniZgtQiUgsiYAPQiaAPiJBIQiNBJhmB9QhmB7guCaQgrCTAPCZQAPCaBHCIQBKCOB8BmQB8BmCZAuQA7ARA8AIIgHAAgAmlr1QC4hjEUAGQCLACBmAWQhfgkiIgLQgigCggAAQjlAAivB2gAIZHMQCxjYgUkTIgCgRQgNiIg/h4QhBh8hthZQhthbiHgoQiCgmiGANQiGANhvA3QBwg7CJgNQCGgOCCAnQCHAnBtBaQDeC3AcEfQAcEei3DfIgGAHIACgDg");
	this.shape_32.setTransform(90.7,135.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#B9BABC").s().p("ApDCvQhHgOg/gcQhEgeg6gtQhchGgOg6IgBgCQArBABjAlQBzAsEBAeQDuAcC5gDIA6gDQCBgDB2gNIAvgGQCxgTCCgdQGzhfj4ijIgJgGQBcAeAVAwQAEAJABAKQAFAkgjAqQhcBukJBIQhcAZh8APQikATjdACIg7ABQk3AAingjg");
	this.shape_33.setTransform(99.3,251.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#7A7B7D").s().p("AhvAeIgBgBIgBgCIgDgmQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAABIACAmIgBACIAAABIAAAAgABzAPIgCgDIgCgmQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAIACADIADAmIgBADIgBAAg");
	this.shape_34.setTransform(92.4,224.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#727375").s().p("AtMB0QgngWgLgdQgTgvBTgfQAVgIAbgIQCOgmEUgaIBKgEIAZgBIAKgBIACAEIAAAAQAEAHAFgBIBPgFIAAABIABgBIDigPIAAABIAAgBIBcgGIADAAIAMgBIAaAAIAYAAQCkgBB9AIQDfAOBgAnQBiApgkBDQgDAGgFAGQgLg8jygoQh5gUiSgJQidgLi5ADIgMAAQg2AFg2gCQj5AJjBAhIgsAIQj8AwABBAQAAANALANIgRgCg");
	this.shape_35.setTransform(97.7,236.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#9A9C9E").s().p("AIvCfQEJhJBchtQAjgqgFgkQAHAlgkAsQhcBtkJBJQhZAYiAAMQB8gOBcgZgAtjA8Qg/g3gPg9IgBgFQgFgjApgfIAugbIATgBQhTAhASAvQAMAdAmAVIARACQAqAuDJAiQD8ArFkgFQFkgFD7gwQD8gxgBhAIgBgGQAFgGAEgGQAjhEhigpIARADIAJADQD4CjmzBfQiCAdixATQA0gHAxgJIsrAVIEAAQQBTACBNgCIg6AEQi5ADjugcQkBgehzgtQhjglgrg/IABACQAOA5BcBHQA6AtBEAeQhdgfg9g1g");
	this.shape_36.setTransform(99.3,250.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#858689").s().p("AgICKIgygDIB+gHIgBACQgGAIgyAAIgTAAgAgLBBIgtgDIB6gHQgDAKg0AAIgWAAgAgQh9Ig4gEIANAAIAQgBIADgBIAMAAIADgBIAMAAIAEAAIAMgBIACAAIANgBIADAAIAMgBIAEAAIAMgBIAEAAIAMgBIADAAIAFAAQgDAMg/AAIgXAAg");
	this.shape_37.setTransform(92,33);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#7E7F81").s().p("AjGBCID3gfQATgGAJgWIAFgUIACAOQABASgDAXQgDAXiKACgABggHQApgWA+gmQgXA0hPAcg");
	this.shape_38.setTransform(97.5,25.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AhQBWQAEgXCKgCQBFgCBFAEQjYAVgeAJQgTAGgJAWQgFALAAAKQgGgTAFglgAgVh/QBHgOBDABQhfADhPAhQgrAShjA8QAghJCSgcg");
	this.shape_39.setTransform(82.7,15.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#78797C").s().p("AoFCjIBdATIABAFIgJAAgAgDCkQACgFAAgFIAHgCIAwgPIBngpQAcgNAbgPIBAgnIA2gmQBkhKBZhnQjXEOkUBWIgbAAIgKAAQAEgCACgEgAlHBHIgTgBIAHAAQBmgDCCgcQEPg5CdiIQgeAgggAbIg2AoIgtAcIgRAJQhxA7iNAWIioALg");
	this.shape_40.setTransform(114.5,207.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#E8E9EA").s().p("AB+CvQCIAKBfAkQhmgWiLgCQkUgFi4BiQDJiHENAUgAByAzQCIAKBfAkQhmgWiLgCQkUgFi4BiQDJiHENAUgABCgPIA3ADIiDAHQADgMBJACgABAhXIA3ADIiDAHQADgNBJADgAggkVQAAgCAEgCIADgCIANgDIADgBIALgBIADAAIANgBIADAAIANAAIADAAIAMAAIAEAAIAEAAIAIABIAAAGIgMABIAAgIIAAAIIgEAAIAAgIIAAAIIgMAAIAAgIIAAAIIgDABIAAgJIAAAJIgNAAIAAgJIAAAJIgDABIAAgKIAAAKIgNAAIAAgJIAAAJIgDABIAAgKIAAAKIgLAAIAAgJIAAAJIgDAAIAAgIIAAAIIgNABIAAgGIAAAGIgDAAIAAgEIAAAEgABBkaIAAgGIADAAIAAAGIAAgGIANABIADAAIAMAAIAEABIAMAAIADABIAGAAIgGAAIAAAAIAAAAIgDAAIAAgBIAAABIgMABIAAgCIAAACIgEAAIAAgDIAAADIgMABIAAgEIAAAEIgDAAIAAgEIAAAEIgNABgABBkagABzkdgABEkgg");
	this.shape_41.setTransform(84.2,42.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#272425").s().p("AgJJkIAGgDIADgJIAVhCIACAAIAgA9IAHAKIAHACIAAACIgfACIAAgCIAGgBQAAgBABAAQABAAAAgBQAAAAAAgBQAAAAAAgBIgBgEIgZgvIgNAsIgCAIQAAAEADABIAGAAIAAACIgXACgAg5JiIABgCIAJgBIACgIIADg0IgCgIIgJgDIAAgCIAjACIAAACIgJACQgCABgBAHIgEAzIACAJIAJACIAAACgAjxItIAAgCIAGACIAEgCIABgEIADg1IgmAjIgCADQgBADABACIAFADIgBACIgVgLIABgBIAFAAIAJgFIA1guIABAAIgDBGQAAAJABACIAEAFIgBACgAEQIZIADgFIgBgKIgThDIACgBIBIAmIAGgCIABACIgYASIgCgCIAFgEIAAgEIgDgDIgvgaIANAtIADAIQACADADgBIAFgDIABACIgTAOgAlEH8IABgCIAJAEIAHgGIAcgrIADgIIgGgGIABgCIAcATIgBACQgGgEgDAAIgGAGIgcArIgDAHQAAAEAGADIgCACgAlnHhIABgCQAGAEADAAQADAAAEgFIAfgoIAEgIIgGgHIABgCIAbAVIgBACQgGgEgDAAQgCgBgEAGIggAoQgDAFAAADIAFAIIgBABgAniFfIACgBIAEAFIAEAAIADgDIAbgvIgzAOIgCACQgDACABADIACAFIgBABIgOgTIABgBIAFADIAKgBIBEgSIABACIgiA8IgFALIACAGIgCABgAH2FGIABgGIgGgIIgtg1IAAgBIBGAEIALgBIAGgEIABABIgOAbIgCgBIADgGIgDgEIgDgBIg2gDIAjAmIACACIAGAAIADgFIACABIgLAVgAoVEPIACgBQADAGADAAIAIgCIAtgZIAGgGIgCgJIABgBIARAeIgCABIgHgHIgIACIgsAaIgHAFIADAJIgBABgAooDnIACgBIAFAHIAIgBIAvgWQAGgCABgDIgCgKIACAAIAOAfIgCAAIgFgHIgJACIguAVIgHAGQgBACADAHIgCABgAIeD0QADgHgCgDQAAgCgGgCIgxgSIgIgBIgFAHIgCAAIAMggIACABQgCAGABADQABADAGACIAwASIAIABIAGgIIACABIgMAggAo4C9IACAAIAFAHIAJgBIAwgRIAHgFIgBgKIACAAIALAgIgCAAIgFgHIgJABIgwARQgEACgDADQAAADACAHIgCAAgAITAnIAAgiIABgBIADAKIAIACIAzgBIAIgCIACgJIADAAIAAAiIgCAAIgDgJIgIgCIgzAAIgIACIgCAKgAgcAcQgJgIgFgLQgCgGAAgFQgCgTAMgPQAMgOATgCQASgCAOAMQAPAMACATIAAAGQAAAOgLAMQgMAPgSACIgFAAQgQAAgMgKgApcADIACAAQAAAHACACIAIABIA0gEIAIgCIABgJIACAAIADAhIgCAAIgDgIIgJgCIgzAEIgIADQgBACAAAHIgCAAgAITAAIgDghIACAAIACAJIAJABIAzgEQAHAAABgCIACgKIABAAIADAiIgCAAIgCgJIgJgBIgzAEQgHAAgBADQgBACgBAGgAoUgFIgCgIIgggcIgjAWQgCADgBAGIgCAAIACgjIACAAIAAAHIADACIAEgBIAUgMIgUgSIgCgBIgEADIgBAFIgCAAIACgbIABAAIABAHIAJAKIAVASIAggUIAHgGIACgHIACABIgBAhIgCAAIgBgHIgCgCIgHADIgVANIAQAOIAJAHIAEgDIABgGIACAAIgBAbgAIJhHIADAAIAEAJIAIAAIAygIQAGAAACgDIABgJIACgBIAFAiIgCAAQAAgGgEgCIgIgBIgyAIQgHABgBACIgBAKIgCAAgAHSkHIACgBIAHAHIAIgCIAsgaIAGgGIgCgJIABgBIARAdIgBACIgHgHQgEgBgEADIgtAaQgFADAAADQgBACADAHIgBABgAnWj5IACgHIgNgpIgpACIgIAFIgBgBIASgdIACABIgCAGQgBABAAAAQAAABAAAAQAAABABAAQAAAAAAABIAEABIAYAAIgGgUIgCgGIgCgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAIgEAFIgCgBIAPgXIACABIgDAHIADANIAIAaIAmgBIAJgBIAGgFIABABIgSAdIgDgCIAEgGIgBgDIgHgBIgaAAIAJAbIACAEIAFgBIAEgEIACABIgOAWgABIkKIAPgXIgPgBIgFABIgEACIgBAAIAEgGIAaABIAAAAIgPAagAG8knIADgBIAGAHIAIgDIArgdIAGgGIgEgJIACgBIATAcIgCABIgGgGQgDAAgFADIgrAcQgFAEgBADIAEAIIgCACgAAikLIAAgBIAFgBIACgCIAAgSIAAgBIgCgBIgFABIAAAAIAMgEIABAAIgBAYIABACIAGABIAAAAgAgFkMIANgDIAFgFIADgDIgBAAIgGABIgDAAIgIgCQgEgCAAgEQABgEAEgCIAJgDQAIAAADAEIAEAIIgCAFIgFAGIgMAEIgIAAgAACkkQgCABAAAEIABAFIAHADIAFgBIADgBIABgBIAAgCIgCgHIgHgDgAgjkNIAAgBIAGAAIABgDIAAgTIgCgBIgFABIAAAAIAMgEIABAAIABABIgCAXIACACIAFABIAAAAgABNkwIgSgFIA6AAQgJAGgQAAIgPgBgAhPkxIgCAAIA2gFQgPAGgTAAIgSgBgAC9k2Ig4ADIgJgDIAFAAQAkgEAGgFIADAAIAvALIABACIgDACgAgLk4IAGgBIAnADIACAAIgkACgAh8lHIAAAAQgbgFgbgQQAAAAAAgBQgBAAAAAAQAAgBABAAQAAAAAAgBIAEAAQARAMAWAIIAJgCQgFgTAcgYQAQgOAbAEQAcAFgOAYQgTAigsgDIgGAAQAFAMAMAGQgSgGgIgNgAh2lWIABAHIA5gOQAJgHgBgKQAAgKgKgEQgEgCgFAAQgVAAgaAogAB5k4IgDgEQgCgHAIgJIACgBQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAQgBANgGAHIADACIgHABgAAkk2IAMgHIACABIAJAHgAgRk7IAGADIgQACgAgLk4gAgRk7IgIgJQgGgNAQgPIACgBIACABQALAXgRAOgAA1lPIADgBIACACQgCAKgIAHQgGgJALgJgAArllQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQA6AIAjgSIAEAAIgBADQgZANgmAAQgQAAgTgDgAkzm1IAEgGIAHgqIglgRQgFgBgFADIgBgCIAegRIABACIgFADQgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAIACADIAVAKIAEgUIABgGIgBgDQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBABIgFACIgBgCIAXgOIABACIgFAFIgEANIgDAbIAjAQIAIACIAGgBIABACIgdARIgBgCIAGgEIAAgEIgFgEIgXgLIgEAdIAAAEIAFACIAFgDIABACIgWAOgAD5nbIABgCIAJADIAGgFIAdgqIADgIIgGgHIABgCIAcATIgBACIgJgDQgDAAgDAFIgdAqQgFAGABACIAHAHIgBACgAjqneIAIgGIgCgIIgVgvIgEgHIgKACIAAgCIAegOIABACIgHAGQgBADADAFIAUAvQADAGACABIAJgCIABACIggAOgAhUoTIAHgEIAYgjIgcgfIgIgCIgBgCIAjgEIAAADIgHABIgBADIABAEIAQASIAOgWIAAgDIgDgDIgFAAIAAgCIAbgDIAAACIgHADQgEACgEAIIgQAWIAaAeIAGAGIAHABIAAACIghADIgBgCIAHgBIACgDIgEgGIgQgUIgPAYIgBAFQAAAAAAABQAAAAAAABQABAAAAAAQABABABAAIAGAAIAAACIgaADgAAloXIAAgCIAJgBIAEgIIAFgzIgCgIQgBgCgHgBIAAgCIAiADIAAACIgJABQgCACgCAGIgFAzQAAAHABACIAJADIAAACgAAAoYIAAgCIAIgCIACgIIABgzIgBgIIgKgDIAAgCIAjABIAAACIgJACIgCAIIgCAzQAAAHACACIAJACIAAACg");
	this.shape_42.setTransform(91,138.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#505052").s().p("AAMKEQgEAAgCgDQgDgCAAgEQgBgEADgDQACgCAEAAIAJAAIAGACIADAGQAAAJgJABgAgnKDIgJgBIgFgCQgEgDABgFQABgJAIABIAJABQAEAAACADIACAGQAAAJgHAAIgCAAgABCJ+IgEgHQAAgEACgCQADgDADgBIAJgBQAEAAACACIAEAGIgCAHQgCADgEAAIgJABgAhkJ8IgIgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgEgDAAgFQACgJAJACIAIABQAJABgBAJQgBAIgIAAIgCAAgAB9J0IgDgFQgBgEACgDQACgDAEgBIAIgCIAHACIAEAGIgBAGIgGAEIgJACIgCAAQgCAAgDgCgAioJtIgDgCQgEgDABgGIAEgFIAHgBIAIACIAGAEIABAHIgEAFIgHABgAC3JlIgDgEQgBgEACgDIAFgEIAIgDIAHAAIAEAGQADAIgIADIgJACgAjhJbIgDgCQgFgEACgGIAFgFQADgBAEABIAIADIAFAEIAAAIIgEAEIgHABgADvJRIgCgEQgCgDACgEQABgDADgCIAIgDQAEgCADACQAEABABADIAAAHIgFAGIgIADgAkRJHIgIgEIgCgCQgGgEAEgHIAFgEIAHABIAHADQAIAEgDAIQgCAGgFAAIgFgBgAElI3IgCgDQgCgDABgEIAFgFIAHgEIAHgBQAEABACADQACADgCAEIgEAGIgIAEgAlHIqIgIgFIgBAAQgFgGADgGQADgDADgBIAHABIAHAEIAEAGIgBAHQgCAFgFAAIgFgCgAFZIYIgCgCIgBgGQAAgEAEgDIAHgEIAGgCIAGAEQAFAIgHAFIgHAFgAl6IIIgHgFIAAAAIgDgGQgBgDACgDIAGgDIAHABIAHAFIADAGIgBAHIgGADgAGJH1IgBgBQgDgEABgDQAAgEADgDIAHgFQAHgGAGAIIACAGIgEAGIgGAGQgDACgDAAQgDAAgDgCgAmpHjIgHgGIgDgHQAAgEADgCIAMAAIAHAFQAGAGgFAHIgNABgAG1HMQgCgCAAgEQAAgEACgDIAGgGIAAAAQADgCAEAAQAEgBACADIADAHIgDAGIgGAGIgMAAgAnUG5IgBgBIgGgGQgGgHAHgGIANAAIAFAHIADAGIgDAGIgGADgAHfGhIAAgBIgEgFQAAgFADgCIAFgHQAGgHAHAGQAHAGgGAHIgGAGIgGAEgAn7GLIgBgBIgGgHIgBgHQAAgDADgCIAHgCQADABADACIAFAHIACAGIgEAGQgCADgDAAQgDAAgDgDgAHzGJIgBAAIgDgHQAAgDACgDIAFgHQACgDAEgBIAHACIADAGIgCAHIgFAHIgGADgAodFbIgCgDIgFgHIgBgHQABgEADgCQAIgEAFAIIAEAGQAFAJgIAEgAIVFYIgBgBIgDgFQAAgEACgDIAEgHQACgDAEgBIAGABIAFAFIgCAHIgEAIIgGAEgAo7EnIgCgDIgEgIIgBgHIAFgGQAIgDAEAIIAEAHQACADgCAEIgEAFgAI0EkIgCgBQgFgFACgGIAEgIQAEgIAIAEIAFAFIAAAHIgEAIQgDAFgEAAIgFgBgApUDwIgCgEIgDgIQgEgJAJgDQAJgDADAJIADAIQADAHgJAEgAJNDuIgDgCQgFgEACgGIADgIQAEgIAIADQAJADgEAIIgDAJQgCAGgFAAIgEgBgApnC3IgDgFIgCgIQgCgKAIgBIAHABIAEAFIADAIIgBAHIgGAFgAJdCzQgEgDABgGIACgJIAFgEIAGgCIAGAFIABAHIgDAIIgEAFIgHABgAp1B8IgDgFIgBgJQgBgDACgDQACgDAEgBIAHABIAEAGIABAJQABAJgIABIgCABQgDAAgDgDgAJvB7IgFgCQgEgEABgEIACgJIAEgGIAGgBQAJABgBAJIgCAIQgBAIgHAAIgCAAgAp9BBQgCgCgBgEIgBgIQAAgFACgCIAGgDIAHACIADAGIABAJQABAIgJABIgCAAQgCAAgDgCgAJyA9IgDgHIABgJQAAgEADgCQADgCADAAQAKABgBAIIgBAJIgDAGIgHACgAqAAGQgDgDAAgEIAAgJIADgGQADgCADgBQAEAAADADIACAHIAAAIIgCAGIgHADgAJ1ABQgEgBAAgEIAAgIQAAgEADgDQADgDADAAIAHADIACAGIAAAJQABAHgJABgAp4g0IgFgCQgDgDAAgFIABgIIADgGQADgCAEAAQAEABACADIACAGIgBAIIgDAGQgCADgDAAIgCgBgAJxg5QgDgDAAgDIgBgJQAAgDACgDQADgDADAAQAEgBADACIADAHIABAIIgCAHIgGADQgEAAgDgCgAp0hxQgEgDABgFIABgJIAEgFIAHgCQAJACgCAJIgBAIIgEAGIgHABgAJoh1IgDgEIgBgJQgBgDACgDQACgDAEgCIAGACIAEAFIACAJIgBAHIgGADIgCABQgDAAgDgDgApmirQgEgEABgFIADgJIAEgFIAHgBQAIACgCAKIgDAIIgEAFIgHAAgAJaiuIgDgFIgDgIQgCgJAIgDQAJgCADAJIACAIIAAAGIgGAFgApQjiIgCgBQgGgFADgGIADgIQAEgJAIAEIAFAFIAAAHIgDAHQgCAHgGAAIgEgBgAJGjnIgDgEIgDgIQgBgDABgEIAFgEQAIgEAEAIIADAIIAAAHIgFAGgAo4kZIgCgBQgFgFADgHIAEgHIAGgFIAGABIAFAGQABADgCAEIgEAHQgCAFgEAAIgGgBgAItkeIgCgDIgEgHQgCgEABgDIAEgFQAIgEAFAHIAEAIQADAIgHAEgAoblOIgBAAQgGgFAFgHIAEgHQAGgHAHAEIAEAGIgCAHIgEAHIgGAEgAIPlRIgCgDIgFgGQgCgEABgDQAAgEAEgCIAGgBQAEAAACADIAFAHQACAEgBADIgEAGgAn5l/QgDgCAAgEQgBgEADgDIAFgHQAGgGAHAFQAHAGgGAHIgFAGQgDAFgEAAQgDAAgDgDgAHsmCIgCgCIgFgGQgGgHAHgGQAHgGAGAIIAFAHIACAGIgDAGQgDACgCAAQgDAAgDgCgAnVmzQAAgEACgDIAGgGQADgCAEAAQAEAAACACQAGAGgGAHIgFAGIgNAAgAG+m2IgDgGQAAgEADgDIAMABIAGAGIADAGIgDAGIgMABgAmnnWIgBgBQgCgDAAgEQAAgDADgDIAHgFIAMABQAGAGgHAGIgGAGQgDADgDAAQgDAAgDgDgAGSneQgDgCAAgEQgBgEADgDIANgBIAGAFQAHAGgGAHIgMACgAl4n7IgBgCIgCgGQABgEADgDIAHgEIAHgCIAFAEQADACgBAFIgEAFIgHAFQgDACgCAAQgDAAgDgCgAFqn9IgHgFIAAAAQgHgFAFgHQAFgIAHAFIAIAFIADAGIgBAHIgGAEgAlGocIgCgCQgCgDABgEQABgDAEgDIAHgEIAHgBIAGAEIABAHIgFAGIgHAEgAE4odIgIgFQgGgFAEgHQACgDADgBIAHABIAHAEIAFAGIgBAHQgDAFgEAAIgGgCgAkQo4IgDgDQgBgDABgEIAFgFIAIgDQAIgEADAIQACADgBAEIgFAFIgIADgAEEo4IgIgDIgCgCQgFgEADgHQADgHAJADIAHADIAFAGIAAAGIgFAFgAjZpPIgDgEQgCgIAIgDIAIgDQAEgBADABIAFAGIgBAHIgFAEIgIADgADNpOIgIgDIgDgCQgEgDABgGIAFgGIAHAAIAIADQAIACgCAKQgDAGgFAAIgEgBgAifpfIgDgGQgBgDACgDIAFgEIAJgCIAGABIAFAFIgBAHIgGAEIgIACgACMphIgDgCQgFgCABgHQADgIAIABIAJADQAJACgDAJIgEAFIgHABgAhlpsIgDgFIACgGQACgDAEgCIAIgBIAHACIAEAGQABAIgJACIgJABgABSprIgEgCQgEgEAAgFIAEgGIAHgBIAIABIAGAEQADADgBAEIgEAFIgGACgAgppxQgDgDAAgEQgBgEADgDQADgCADAAIAJgBQAEgBACADIADAHIgCAGIgGADIgJABgAAgpwIgJAAIgFgCQgDgDAAgEQAAgEACgDQADgCAEAAIAJAAQAJABgBAJIgDAGQgCACgDAAIgBAAg");
	this.shape_43.setTransform(91.1,138.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#96989A").s().p("AkDHNQixg0iPh2QitiPhXjMQgbhAgRhBIgYiEIgBgKQgHhHAFhJQgGDQBUC+QBXDDCnCJQCQB2CxA0QAiAKAjAIQgCAFABAGIABAHIhdgTIBVAYIgZACIgmgLgALzBgQhZBnhkBKQBNg9BAhOQBehyA1iHQAjhdAPhhQAHgqACgqQgECWgzCMQg1CQhjB4Qh2CQikBVQhCAjhGAXIgYABQEVhWDWkPg");
	this.shape_44.setTransform(90.8,179.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#B7B8BA").s().p("AoVhTIAIgKIAPgQIDGiZQBvg2CGgNQCGgNCCAmQCHAoBsBaQBtBaBCB7QA/B4ANCIIABARQgMhzgthiQg/iMiBhqQhthaiGgoQiCgmiHANQkfAci2DeQiPCtgPDUQAGjnCZi5g");
	this.shape_45.setTransform(90.8,100.8);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#CEC2AD").s().p("AptG9QgdhSgJhdQgFgvABgsQAPjUCOitQC3jfEfgcQCGgNCCAnQCHAnBtBaQCBBqA/CNQhCh0hrhXQhxhdiJgsQiFgpiIAKQiKAKh4A8Qh9A/hYBsQhwCIgdCuQgdCpA3CnIgHgQgAAEEMQgNgNgCgSIAAgGQAEALAIAIQAPAMATgCQATgCAMgPQAKgMABgPQACAFAAAHQACATgMAOQgMAPgTACIgFAAQgQAAgNgKg");
	this.shape_46.setTransform(87.9,116.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#F8E8CD").s().p("Am9H5QiXh7g9irIAHAQQg3inAdipQAdivBwiIQBYhsB9g+QB4g9CKgKQCIgKCFAqQCJArBxBdQBrBYBCB0QAtBiAMBzQAVETixDYIgDACIgPATIjICcQhxA3iHANQgmAEgkAAQjxAAjBifgAABJmQgCADABAEQAAAFACACQACACAEAAIAIAAQAJgBAAgJIgDgGIgGgCIgJAAQgEAAgCACgAg8JqQgBAFAEADIAFACIAJABQAIABABgKIgCgGQgCgDgEAAIgJgBIgCAAQgHAAAAAIgABLJfIgJABQgDAAgDADQgCADAAAEIAEAGIAGACIAJgBQAEgBACgDIACgGIgEgGQgCgCgDAAIgBAAgAh4JiQAAAFAEAEQAAAAABAAQAAABABAAQAAAAABAAQAAABABAAIAIABQAJABACgIQABgJgJgCIgIgBIgCAAQgIAAgBAHgAB9JWQgEABgCADQgCADABAEIADAFQADADAEgBIAJgCIAGgEIABgGIgEgGIgHgBgAiuJPIgEAGQgBAGAEADIADACIAJACIAHgBIAEgGIgBgGIgGgFIgIgCgAgFJMIgEAJIgGACIABACIAWgBIAAgCIgGgBQgCAAAAgEIABgIIANgtIAZAvIABAEQAAABAAAAQAAABAAABQAAAAgBAAQgBABAAAAIgGABIAAACIAfgCIAAgCIgHgCIgGgJIghg+IgBAAgAC2JIIgFAEQgCADABAEIADAEIAIACIAJgDQAIgCgDgJIgEgFIgHgBgAg6IMIAJADIABAIIgDAzIgCAIIgJACIgBACIAiACIABgCIgJgDIgCgIIADgzQABgHACgCIAJgBIAAgCIgigCgAjmI8IgFAFQgCAGAFAFIADABIAIADIAHAAIAEgFIAAgHIgFgFIgIgDIgEgBIgDABgAD1IwIgIADQgDACgBADQgCAEACADIACAEIAJABIAIgDIAFgFIAAgHQgBgEgEgBIgDgBIgEABgAkhIpQgEAGAGAFIACABIAIAEQAIAEAEgJQADgHgIgFIgHgDIgHgBgAj3IgIAbAOIABgBIgEgFQgBgDAAgJIADhFIgBgBIg0AuIgJAGIgGgBIgBACIAVALIABgCIgEgDQgCgDABgDIACgDIAmgiIgDA1IAAAEIgFACIgFgCgAEqIWIgHAEIgFAFQgBAEACADIACADIAKABIAIgEIAEgGQACgDgCgDQgCgEgEgBgAlWILQgDAHAFAFIABABIAIAEQAIAFAEgIIABgHIgEgFIgHgFIgHgBQgDABgDADgAD6G6IASBEIABAKIgDAFIABABIATgOIgBgCIgFADQgDABgCgDIgDgIIgNgsIAvAaIADACIAAAFIgFAEIACACIAYgTIgBgBIgGACIhIgngAFdH3IgHAFQgEACAAAEIABAGIACACIALABIAHgFQAHgFgFgIIgGgDgAlJHwIAcATIABgCQgFgEgBgDIADgIIAcgrIAGgFQAEAAAFADIABgCIgcgTIgBACIAGAHIgDAIIgcArIgGAFIgJgDgAmHHpQgCADABADIADAGIAAABIAHAFIAHABIAGgDIABgHIgDgGIgHgFIgHgBgAlsHVIAaAVIACgCIgGgHQAAgDADgFIAggoQAEgGADABQADAAAFADIACgBIgbgVIgBABIAFAIIgDAHIggApQgDAFgEAAQgDAAgFgEgAGMHTIgHAGQgDACAAAEQgBAEADADIABABQAGAFAGgFIAGgGIAEgGIgCgGQgEgEgDAAQgDAAgDACgAm0HCQgDADAAAEIADAGIAHAGIAAAAIANgBQAFgHgGgGIgHgFgAGxGxQgCADAAAEQAAAEACACIABABIAMgBIAGgGIADgGIgDgHQgCgCgEAAQgEAAgDADIAAgBgAnfGkIAGAHIABAAIAGACIAGgCIADgGIgDgHIgFgGIgNgBQgHAHAGAGgAHfGAIgFAGQgDADAAAEIAEAGIAAAAIAGACIAGgDIAGgHQAGgHgHgGQgEgCgCAAQgEAAgDAEgAoEFpQgDACAAAEIABAGIAGAHIABACQAGAEAFgEIAEgGIgCgHIgFgGQgDgDgDgBgAHyFnIgFAHQgCADAAAEIADAGIABAAIAGACIAGgEIAFgHIACgHIgDgGIgHgBQgEAAgCADgAnoFTIASAZIACgBIgCgHIAFgLIAig8IgBgBIhDARIgLABIgEgDIgCABIAOATIACgBIgDgFQgBgCADgDIADgBIAygOIgbAuIgDADIgEAAIgEgEgAolE3QgDACgBADIABAHIAFAIIACACIAKAAQAIgEgFgIIgEgHQgEgFgEAAIgFACgAITE2IgEAIQgCACAAAEIADAFIABABIAHABIAGgEIAEgHIACgHIgFgGIgGgBQgEABgCADgAG+D3IAuA0IAFAJIgBAGIACABIALgVIgCgBIgDAEIgFABIgDgCIgignIA1AEIAEABIACAEIgDAFIACABIAOgbIgBgBIgFAFIgMAAIhFgEgAobECIARAeIABgBIgCgJIAGgGIAtgZIAIgCIAGAHIACgBIgRgeIgBABIACAJIgGAGIgtAZIgIACQgDgBgDgGgApBECIgFAFIABAHIAEAIIACADIAKABIAEgGQACgDgCgEIgEgHQgDgGgFAAIgEACgAIvECIgEAIQgCAGAFAFIACABQAHAEAFgIIAEgIIAAgHIgFgFIgFgBQgFAAgCAFgAouDaIAOAfIACgBQgDgGABgDIAHgFIAugWIAJgBIAFAHIACgBIgOgfIgCABIACAJQgBADgGACIguAWIgIACIgGgIgAHjDHIAwASQAGADABACQABACgCAHIACABIAMggIgCgBIgGAIIgIgBIgwgSQgGgCgBgDQgBgDACgGIgCgBIgMAgIACABIAFgIgApYDKQgJAEAEAIIADAIIACAEIAJABQAJgDgDgIIgDgIQgDgGgFAAIgEAAgAJGDMIgDAIQgCAGAFAEIADACQAIADADgIIADgJQAEgHgJgEIgEgBQgFAAgDAGgAo+CxIAMAgIACgBQgCgHABgCQACgDAFgCIAwgSIAIgBIAFAIIACgBIgLggIgCABIABAJIgHAFIgwASIgJABIgFgIgApwCcIACAJIADAEIAIACIAGgFIABgGIgDgJIgEgFIgHgBQgIACACAJgAJdCPIgFAFIgCAIQgBAGAEAEIADABIAHgBIAEgFIADgIIgBgHIgGgEgAp8BaQgCADABAEIABAIIADAGQAEADAEgBQAIgCgBgJIgBgIIgEgGIgHgCQgEABgCADgAJpBUIgEAGIgCAJQgBAEAEAEIAFACQAIACACgJIACgJQABgJgJgBgAqDAeQgCADAAAEIABAIQABAEACACQADADAEgBQAJgBgBgIIgBgJIgDgGIgHgCgAJvAZQgDADAAAEIgBAIIADAIIAFACIAHgCIADgGIABgJQABgJgKgBIgBAAQgDAAgCACgAgJhBQgTACgMAPQgMAOACATQAAAHADAFIAAAFQACATAOAMQAPAMASgCQATgCAMgOQAMgPgCgSQAAgGgCgGIgBgGQgCgTgPgMQgMgKgPAAIgFAAgAINgHIAAAhIACAAIACgJIAIgCIA0AAIAIACIACAJIACAAIAAghIgCAAIgCAIIgIACIg0AAIgIgCIgCgIgApigIIACAhIACgBQAAgGACgDIAIgDIAzgDIAIABIADAJIACAAIgCghIgCAAIgCAJIgIADIgzADIgIgBQgCgBgBgIgAqEgeIgDAHIAAAIQAAAFADADIAGACIAHgDIACgGIAAgJIgCgGQgDgDgEAAQgDAAgDACgAJwghQgDADAAAEIAAAIQAAAEAEADIAGACQAJgBgBgIIAAgJIgCgGIgHgDQgDAAgDADgAINgLIACAAQAAgHABgDQACgCAGAAIAzgFIAJACIACAJIADAAIgDgiIgCAAIgCAJQgBACgHABIgzAEIgIgCIgDgIIgCAAgAocgZIACAHIACAAIABgaIgCgBIgBAGIgDADIgKgGIgQgPIAWgNIAGgCIADACIAAAHIACAAIACgiIgCAAIgDAHIgGAFIghAVIgUgSIgJgKIgBgIIgCAAIgCAcIADAAIAAgGIAEgCIACABIAVARIgVANIgEABIgDgDIAAgGIgCAAIgCAiIACAAQABgGADgCIAigXgAIJgxIACgBIABgJQABgCAHgBIAzgJIAIABQADACAAAHIADAAIgGgiIgCAAIgBAKQgBACgGABIgzAIIgIgBIgEgIIgCAAgAqAhaIgDAGIgBAJQAAAEADAEIAFACQAEAAADgCIADgGIABgJIgCgGQgCgDgEgBIgCAAQgCAAgDACgAJxhfQgDAAgDADQgCADAAAEIABAIQAAADADADQADACAEAAIAGgDIACgHIgBgIIgDgGQgDgCgDAAIgBAAgAp2iVIgEAFIgBAJQgBAFAEADIAEACIAHgBIAEgGIABgIQACgJgJgCgAJhiWQgCADABADIABAJIADAFQADADAFgBIAGgEIABgHIgCgIIgEgGIgGgBQgEABgCADgApmjQIgEAFIgDAJQgBAFAEAEIADACIAHgBIAEgFIADgIQACgJgIgDgAJWjUQgIACACAJIADAIIADAFIAIABIAGgEIAAgHIgCgIQgCgHgGAAIgEABgApWkEIgDAIQgDAGAGAFIACABQAJADADgIIADgIIAAgHIgFgFIgEgBQgFAAgDAGgAJBkMIgFAFQgBADABAEIADAIIADADIAJACIAFgFIAAgHIgDgIQgDgGgFAAIgEABgAHMkTIASAdIABgBQgDgHABgCQAAgDAGgDIAsgZQAFgEADABIAHAHIABgBIgRgeIgBACIACAIIgGAGIgsAaIgIACIgHgGgAnakNIgCAIIACABIAOgWIgCgBIgEAEIgEAAIgCgDIgJgcIAZAAIAHACIABADIgDAGIACABIASgcIgBgBIgGAEIgJACIgmAAIgIgZIgDgOIADgGIgCgCIgPAXIACABIAEgEQAAgBAAAAQABAAAAAAQABAAAAAAQABAAABABIABACIADAGIAGATIgYABIgEgCQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBABAAIADgGIgCgBIgTAdIABABIAIgGIApgBgABRkuIgOAXIAEABIAQgaIAAgBIgaAAIgEAFIABABIADgDIAFAAgAG3kzIATAcIACgBIgEgJQABgDAFgDIArgdQAFgDADABIAHAGIABgBIgTgdIgBACIADAIIgGAHIgqAcIgIADIgHgGgAAjkvIAAACIAAASIgCACIgFAAIAAABIATABIAAgBIgFgBIgBgCIAAgXIAAAAIgNADIAAABIAFgBgAAKkkIgDAEIgFAEIgMADIAAABIAJgBIALgEIAFgFIACgGIgDgIQgEgDgIAAIgJACQgEACgBAFQAAADAEACIAIADIADAAIAGgCgAgikwIAAATIgBACIgGABIAAAAIATABIAAgBIgFAAIgBgCIABgYIgBAAIAAAAIgNADIAAABIAFgBgAo8k7IgEAIQgDAGAFAFIACABQAJAEADgIIAEgHQACgEgBgDIgFgFIgGgBgAImlCIgEAFQgBAEACADIAEAIIACADIAKABQAHgEgDgJIgEgHQgDgGgFAAIgFACgABHk9QAcAEANgJIg7AAgAhXk9IADAAQAeAEAVgJgADVk9IADgBIgBgCIgvgMIgDABQgGAFgkADIgFABIAJACIA5gCgAgFlAIAjgCIAXAAIgJgGIgBgBIgNAHIgCAAIgmgEIgHACIgGgEQASgNgMgXIgCgBIgCABQgQAPAHANIAHAIIgKAGIAQgCgAhnlBQgNgFgFgNIAGABQAsACATghQAPgZgdgEQgbgEgQAOQgcAYAFASIgJACQgVgHgSgMIgDAAQgBAAAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAaAQAbAFIABABQAHAMATAGIAAAAgAB2lZQgIAJACAHIADAFIgDACIAGAAIgDgCQAHgIAAgMQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAgAAwlcQgMAKAHAJQAHgHACgLIgCgCgAodlvIgEAHQgFAHAGAFIABABIAHABIAGgEIAEgHIACgHIgEgGQgDgCgDAAQgEAAgDAFgAIHl1QgEACAAAEQgBAEACADIAFAHIACACIAKAAIAEgFQABgEgCgDIgFgHQgCgEgEAAgAAklzQgBAAAAAAQAAABAAAAQAAAAABAAQAAAAABABQA+AIAkgTIABgCIgDAAQgjASg7gJQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAAAABgAn5mgIgFAHQgDADABADQAAAEADACQAHAGAGgHIAFgHQAGgHgHgFQgDgDgDAAQgEAAgDAEgAHimlQgHAGAGAHIAFAHIACABQAFAFAGgFIADgGIgCgGIgFgHQgDgEgEAAQgDAAgDACgAnRnOIgGAHQgCACAAAEIADAHIANgBIAFgGQAGgHgGgGQgCgCgEAAQgEAAgDACgAG3nKIADAGIAGAHIAMAAIADgHIgDgGIgGgGIgMgBQgDADAAAEgAlToCIAlARIgHAqIgEAFIABACIAXgNIgBgCIgGACIgEgBIgBgFIAEgcIAXALIAFAEIAAADIgFAEIABACIAdgRIgBgCIgHACIgIgDIgjgQIAEgaIADgOIAGgEIgBgCIgYAOIABABIAFgCQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABIABACIgBAHIgDAUIgWgKIgCgDQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAIAFgEIgBgCIgeASIABACQAEgDADAAIADABgADznoIAcATIABgBIgGgHQgBgDAEgFIAdgqQADgGADAAIAJADIABgBIgcgUIgBACIAGAHIgDAIIgdAqIgGAGIgJgEgAmrnxQgDACAAAEQAAAEACACIABABQAGAFAGgFIAGgFQAHgGgGgHIgMgBgAGNn5QgDADABAEQAAAEADACIAHAGIAMgBQAGgHgHgGIgGgGgAj+ooIAUAvIACAJIgIAFIABACIAfgNIgBgCIgJABQgCAAgDgGIgUgwQgDgEABgEIAIgFIgBgCIgfANIAAACIAKgCgAl0ocIgHAFQgDACgBAEIACAGIABACQAFAEAGgEIAHgEIAEgGQABgEgDgDIgFgEgAFdocQgFAHAHAFIAAAAIAHAFIAHACIAGgEIABgHIgDgGIgIgFQgDgCgCAAQgEAAgDAFgAhgpqIABACIAJADIAbAfIgYAjIgHADIABACIAagCIAAgCIgGgBQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgEIAPgYIARAUIADAFIgCADIgHACIABACIAhgDIAAgCIgHgCIgGgGIgZgdIAPgXQAEgHAEgDIAHgCIAAgCIgbACIAAADIAGAAIADADIgBACIgOAXIgQgTIgBgDIACgEIAGgBIAAgCgAAnptQAHABACACIABAJIgFAzIgDAIIgJABIgBACIAiADIABgCIgJgDQgCgBAAgHIAGgzQABgHACgBIAJgBIAAgDIgigDgAgEpuIAIACIACAIIgBA0IgDAIIgIACIAAACIAhABIAAgDIgJgCQgCgBAAgHIACgzIACgJIAJgBIAAgDIghAAgAlBo9IgHAFQgEACgBADQgBAEACADIACACIALABIAHgEIAFgGIgBgGIgGgFgAEqo7QgEAGAGAFIAIAFQAIAFAFgIIABgHIgFgFIgHgFIgHgBQgDABgCAEgAkKpYIgIADIgFAFQgBAEABADIADAEIAJABIAIgEIAFgFQABgDgCgEQgCgFgFAAIgEABgAD0pVQgDAGAFAEIACACIAIADIAHAAIAFgEIAAgHIgFgFIgHgEIgFgBQgFAAgCAGgAjSpuIgIACQgIAEACAIIADAEIAJABIAIgCIAFgFIABgHIgFgFIgDgBIgEABgADApvIgFAFQgBAHAEADIADABIAIADQAIADAEgIQACgJgIgDIgIgDgAigp9IgFAEQgCADABAEIADAFIAIABIAIgCIAGgEIABgGIgFgGIgGgBgACBp5QgBAGAFADIADACIAIABIAHgBIAEgFQADgJgJgCIgJgCIgCgBQgHAAgCAIgAhkqJQgEABgCADIgCAGIADAGIAHACIAJgBQAJgCgBgJIgEgGIgHgBgABKqJIgEAGQAAAFAEADIAEACIAJABIAGgBIAEgGQABgEgDgDIgGgEIgIgBgAgfqQIgJABQgDAAgDADQgDADABADQAAAEADADIAGACIAJgBIAGgDIACgGIgDgHQgCgCgDAAIgBAAgAANqOQgCADAAAEQAAAEADADIAFACIAJAAQAEABACgDIADgGQABgJgJgBIgJAAQgEAAgDACgAgDkmIgCgGQAAgDACgCIAFgBIAHACIACAHIAAACIgBACIgDABIgEAAgAgXlIgAh8ljQAggxAZALQAJAEABAKQABALgJAGIg6APg");
	this.shape_47.setTransform(91.5,139.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.6,0.5,194.7,272.3);


(lib.shape13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(39,36,37,0.098)","rgba(68,68,68,0.078)","rgba(206,206,206,0.02)","rgba(255,255,255,0)"],[0.51,0.604,0.878,1],-1.7,-45.2,-18.6,158.7).s().p("AkSYCQiTgeh/hUQh/hVhUh9QhRh5gfiNQgeiOAZiNQAbiRBSh8QBBhhBchHQBYhFBrgnQgmgUgogaQiWhjhjiWQhgiRgiirQgiirAgiqQAiixBkiWQBliXCWhjQCRhfCrgiQCqgiCqAgQCwAhCXBlQCWBkBjCWQBgCRAiCrQAiCrggCqQgiCxhkCWQhbCIiEBdQh/BbiXArIAVANQB/BUBUB9QBRB5AfCOQAeCNgaCNQgaCShSB7QhTB8h8BQQh4BOiPAbQhDANhFAAQhKAAhKgPg");
	this.shape.setTransform(125,191.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(36,36,178.1,310.6);


(lib.sprite23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape22("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sprite23, new cjs.Rectangle(0,0,30.2,24), null);


(lib.sprite20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape19("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sprite20, new cjs.Rectangle(0,0,53.3,25.4), null);


(lib.sprite17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.shape16("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sprite17, new cjs.Rectangle(0,-1,3.9,74), null);


(lib.sprite14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape13("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sprite14, new cjs.Rectangle(36,36,178.1,310.6), null);


(lib.sprite24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sprite23();
	this.instance.parent = this;
	this.instance.setTransform(30.3,23.8,1,1,0,0,0,30.3,23.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:90},100).to({rotation:180},99).to({rotation:270},102).to({rotation:360},100).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,30.2,24);


(lib.sprite21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sprite20();
	this.instance.parent = this;
	this.instance.setTransform(-2.2,25.5,0.999,0.999,1.7,0,0,-0.4,25.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:91.7,x:-2.3,y:25.4},49).to({rotation:181.7,x:-2.1,y:25.3},50).to({rotation:271.7,y:25.5},50).to({rotation:361.7,x:-2.2},52).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.8,0,54,26.9);


(lib.sprite18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sprite17();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:177,guide:{path:[0.1,0.1,12.5,0.2,22.2,4.3,31.9,8.4,38.8,16.4,52.5,32.4,53.9,51.8,55.3,71.2,43.7,88,32.2,104.9,6.8,107.2,6.8,107.2,6.8,107.2]}},56).to({scaleX:1,scaleY:1,rotation:189,guide:{path:[6.7,107.2,0.9,107.7,-4.5,107.3]}},4).to({scaleX:1,scaleY:1,rotation:360,guide:{path:[-4.6,107.4,-23,106.1,-34,94,-48.3,78.4,-49.6,58.3,-50.8,38.3,-38.6,20.4,-26.4,2.4,0,0.1,0,0.1,0,0.1]}},55).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-0.2,3.9,73.2);


(lib.clock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// shape 25
	this.instance = new lib.shape25("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-93.9,-183.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// sprite 24
	this.instance_1 = new lib.sprite24();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-2.4,-85,0.998,0.998,51.9);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,0.2)",2,2,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// sprite 21
	this.instance_2 = new lib.sprite21();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-25,-57,0.999,0.999,-65.7);
	this.instance_2.shadow = new cjs.Shadow("rgba(0,0,0,0.2)",2,2,2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// sprite 18
	this.instance_3 = new lib.sprite18();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-0.9,-46.1,1,1,0,0,0,3.1,54.1);
	this.instance_3.shadow = new cjs.Shadow("rgba(0,0,0,0.2)",2,2,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// shape 15
	this.instance_4 = new lib.shape15("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(-93.9,-183.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// sprite 14
	this.instance_5 = new lib.sprite14();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-136,-163.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.clock, new cjs.Rectangle(-100,-182.9,200.1,366), null);


// stage content:
(lib.Element_watch_time_Canvas = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// clock
	this.instance = new lib.clock();
	this.instance.parent = this;
	this.instance.setTransform(190.2,210.9,0.935,0.935,-30.6,0,0,-18.1,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(576.8,332.7,312.9,389.7);
// library properties:
lib.properties = {
	width: 1070,
	height: 650,
	fps: 24,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;