(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.per5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AAMMnIgWgBQA/hlAzh2QA3h8AqiHQAqiGAgiIQAfiHAXiCQAYiDAQhzIABgJQAngVAvgRQBGgaBWgHIAOgBIC8ByIibhzQBDAABNAPIgbgNQgagOgngbIgbgWIBKhKIhZA9QgTgSgSgUQgogsgdg+IgKgWIgSggIAKAGQAmAUAyAXIAJAEIAhALIBUAdQA0ATA9AaQA9AbA6AfQA6AgAsAkQAsAkATAmIASApQARAoAaBHQAaBIAbBfQAbBeAWBtQAUBuAIB2QAIB1gNB0IgEAMQgFALgRAUQgSATgoAZQAAABg4AWQg4AWhrAgQhEAVhYAUQgtiggIiaQgJidASiPQARiOAfh5QAgh5AhhaQAghZAYgyIAUgtQhbCtgyCgQgxCigRCPIgCAWIAAgIIgBAQIgJCwIgBABIABA1QAFB2AOBVQAPBVANAtIAOAsIhZATQiZAfjBATQikARi+AAIhFgBgAKUhlQhKCbhOCKQhOCJhHBxQhIBwg4BRQg5BSghAsIghAsQBUhWBOhsQBPhrBGh0QBGh2A9hzQA9h0AwhmQAxhoAihQQAjhQASguIATgvIgOgGQhACphMCcgAgeMlIgDgBIgBAAIhjgHIgggqQghgsg3hSQg4hRhHhwQhHhwhNiKQhNiJhLibQhLidhAipIgOAHIASAvQASAtAjBRQAiBQAwBnQAwBnA8BzQA8BzBGB1QBGB1BOBrQBNBqBTBWIgagCQhRgGhpgMQhpgMh5gRQh4gSh8gZQh8gZh2ghQh3ghhngsIgKgEQgKgGgNgQQgNgQgLghQgLghgBg3IACgkIAIhiQAFg+ALhQQALhQAQhYQARhZAZhZQAYhZAihQQAihRArg+IAVgWQAVgVAsgdQAsgdBFgbIAagIQAagHArgPQArgOA1gTQAzgTA1gXIAmgRIgCAEIgLAUQgdA+gnAsIgbAcIhSg5IBEBFQgTASgUAPQgnAbgZAOIgbANQBTgQBIABIiVBuICzhtIAEAAQBWAHBFAYQA4AVAtAbQASBpAXBoQAlCoAtCbQAtCdAsCGQAtCGAlBlQAmBkAWA5IASAtIAAAAIgIAAgAvgluQAiBSAfBwQAgBxASCGQARCIgICXQgICYguChIAMAJQABgBAOgpQANgqAPhNQAOhOAFhuQAEhugRiIQgRiHgyieQgkh0g9h8QAPAhASAtg");
	this.shape.setTransform(139.7,253.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#F4CF96","#C89B6C"],[0.004,0.957],-31.5,0,28.2,0).s().p("AkNFxIgMgCIAMgBQAagDAWgEIAVgGIAPgEIAjgNIgIAFIgCABQgTALgTAHIgWAGIgOADIgIABIgJAAIgSgBgAEWlxIABAAIADAAIAAAAIgEAAg");
	this.shape_1.setTransform(110.7,39.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#E9BD95","#F6DABB","#E9BD95","#E7B78D","#E5B083"],[0.004,0.192,0.655,0.71,0.773],2.2,76.8,2.2,-74.4).s().p("AgLIUQg4g+gwhQQgbgwgYgyQgihMgahVQgbhdgThdQgUhegMhWQgLhWgHhDIgEgqIgCgeIgDgiIgBgWIAAAAIABgEIAEgLIAAgBQAiAlAlAbIARANQBvBLCFAAQCKAABzhSIATgOQAUgQAUgTIAPgPIgCAVIgBAIIgFAuIgCAVIgEAkQgIBGgOBYQgOBYgVBhQgVBggdBeQgVBHgbA/QgtBbgnA3QgpA+gZAaIgYAaIAAgBg");
	this.shape_2.setTransform(138,200.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCCCFF").s().p("ACkGCQAag/AWhHQAdheAVhgQAVhhAOhYQAOhYAIhGIAEgkIACgVIAFguIABgIIACgVIACgCIAJgKIAiAdIASASIAHAHIARARIAEAFQAlApAcAoQAeArAVAjIABACIAKARIADAGIARAgIALAWQAdA+AnAsQATATATASIAPANIAaAVQAnAcAaAOIAbAMQhNgPhDABQgQgBgQACIgPABQhWAHhGAaQguARgoAVIgHAEIgeATQg2AlgnAnQgnAngZAiQgZAjgMAUIgLAUIASgogAiqGOQgMgWgXghQgYghglgmQgfgggpgdIgSgNIgTgMQgugcg4gUQhFgYhVgHIgFAAQgPgCgPABQhIgBhSAPIAagMQAagOAngcQATgOAUgSIAOgNIAagaQAogsAdg+IALgVIABgDQALgUAUgfQAUghAfgpQAWgeAageIARgTIAEgDIAJgLIAUgTQAbgZAegXIABARIAAAAIABAXIADAhIACAfIAEApQAGBDAMBWQAMBWAUBdQASBeAcBdQAaBVAhBMIAGALIgKgSg");
	this.shape_3.setTransform(137.9,189.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D4A57D").s().p("AIohZIAEAAQAEABADAJQACAJgDAZQgEAWgMAnIgCAJIgWBBgAoLBWIgUg8QgKgigFgXIgDgOQgDgZACgJQACgIADgBIACgBIADAAIAQBeQABASAFAOIAFAhIAEAUg");
	this.shape_4.setTransform(139,90.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E9BD95").s().p("AHmC0IArk+IARABQAQAAASgGIAJgDQAFAUgCAeIAAACQgCAkgTA1IgFAVQgFAVgLAfQgHAUgIATIgMAXQgPAfgVATIgBABgAIph4IgeCzIAVhAIADgJQAMgpADgWQAEgZgDgJQgCgJgEAAIgDAAIgBAAgAoSBfQgJgGgJgMIgKgNQgPgYgIgsIgDgTIgGgtQgCgaAAgdQABgcAFgWIAWgBIAMACQAOACANgBIABAPQABAQADAPIgRAAIAJAdIAAAJIgDAOQgEAVAAAXIAAAEIgQhfIgEAAIgBAAQgDACgDAIQgCAIAEAZIACAPQAFAWALAjIAUA8IAFAvIAAAAQgCAAgLgHgAoSAGIACAGIAEAbgApIi0IACABIABAAIgDABIAAgCg");
	this.shape_5.setTransform(138.9,93.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.rf(["#E9BD95","#F6DABB","#E9BD95","#E7B78D","#E5B083"],[0.004,0.192,0.655,0.71,0.773],3.7,-64.4,0,3.7,-64.4,296).s().p("AjxJTIgSgNQglgcgigkQgegggcgmQgUgbgSgcIgFgIIgKgSQgQgcgNgdIgNgfQgdhFgQhLIgJgxIAAAAIgDgWIgBgHQAJAMAJAGQAMAIABgBIgFgvIACAEIgEgUIgEgaIgBgGQgFgPgBgRIAAgEQAAgXAFgVIACgOIAAAHIABAKIACAEIgBANQABACAFAEIAJAFIADADQAFAPAGAHQAGAIAGACIAFACIAAgHIAAACIACARQABANAUALQATALAbAJQAcAIAbAGIAtAIIATADQA9AFAkgFQAlgFASgJQAUgKAGgIIAGgHQAFAFAFgDIABAAQAIgFAHgNIALgVIAFgMQAOgUAMgIQANgIAJgBIADAAIACAAIADAAIADAAQAGABAMAHQANAIANAVIADALQAGALAHAKQAGAMAJAFQAGAEAGgFIAFAIQAGAIATAKQAUAJAkAFQAkAFA8gGIATgDQASgCAcgGQAcgGAagIQAcgJATgLQASgKADgOIACgPIAAADQAAABAKgGQALgHAGgWIAEgDQAFgCAEgDIAGgGIAAgDIAOgEIAGg2IgDgBIgeAOIgGgKIgCgHQgDgHgHgFIgPgDQgPgEgpgBQgpgBhPAGQhOAGh+ASIAAgBIgBgHQgzAFglAAQgmgBgWgCIgVgCIgBAGIgBAAIAAACQhNgLg9gGQgjgFgegCQhOgFgqABIgpACIAAAAIgOADIgCAAQgPADABABIgGAFIgTgBQgDgPgBgQIgBgPIAIgBIAPgCIAVgHQAUgHATgLIACgBIAIgFIAAAAIATgIIAtgdIACgBIACgCIAMgJIgEAGIAJgJQAegaAWgeQAWgeANgVIALgXIAAgWIAOgVIAAAGQgDBMgVAuQgVAvgeAYIgOALIAUgJQAxgXAXgaIABgBQgTAlgaAVIgNAKIATgIQAxgYAXgaQAXgaAGgWQAGgWgCgOIgDgPQAEhSAWg4QAWg3AgghQAlgfAZgPIANgJIAAAAIAAABIAVAJIAIAEQAYANAgAeQAjAhAsA+QApA9AwBiIAEATQAEATAQAZQAQAZAfAVQATAMAZAHIAPAEIAaAEIAAAAIAAAAIgPgFIgJgEIgMgGIgMgHQgUgMgUgVQgVgVgNgfQgNggAAgsIgJgWQgJgXgRgiIgLgVIAFAGQAUAWARAZIAcA4IAEATQAFATAPAYQAQAaAgAUIAFAEIAHAIIAJALIAGAIIAFAGQAdAiAiAZIADABQAhAYAkAIIAGABIgrE+IAAABIAAgBQAVgTAQgfIALgXQgHArgLAoIgBADIgIAcIgBAEQgWBJgiBDIgPAbIgIANQgNAWgPAWIgOATIgCADQgYAhgaAcIgJAKIgCACIgQAPQgTATgVAQIgTAOQhyBSiLAAQiFAAhuhLgAkaAzIgTgDIgsgHQgagGgagIQgbgIgTgKQgSgKgBgOIgDgQIgCglQAAgWACgUIABgHQACgGANgHQAPgGAkAAIAdAAIBMAAIA2ADIAQABIAbADIAEAAIA3AGIADABIAKABIAcAEIAAgDIABAAIATALQAFAJAAAPIAAABIgBAIIAAABIgBAEIAAACQgDARgHARQgIAUgHAOIgIAOIgFAIQgHAIgRAJQgTAJgjAFQgRACgWAAQgYAAgegDgACuA0QgjgFgTgJQgRgJgHgIQgGgIAAgBIgchHIgFgMIAAgDIgBgCIAAgBIAAgBIAAgBIAAgBIAAgDIAAgIIABgCIAAAAIAAgCIAAAAQAFgMAJgEIAIgEIAUgEIAGgBQAbgEAqgEQAdgEAdgCIAugCIBLgBIAfAAQAjAAANAGQAPAHACAGQACAHgCAAQADAVgBAVQAAAWgCAPIgBAQQgCAOgSAKQgTALgaAHQgbAJgaAFIgrAIIgTADQggADgZAAQgVAAgQgCg");
	this.shape_6.setTransform(138.2,95.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#C89B6C","#F4CF96","#E9BD95"],[0,0.969,1],-21,-1.1,40.6,-1.1).s().p("ADOB5IADAHIABAIIgEgPgAi8h9IgWgJIAAgBIAYALIAGADIgIgEg");
	this.shape_7.setTransform(158.6,42.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#BDBDBD","#E0E0E0","#D7D7D7"],[0,0.969,1],-30.1,10.6,31.4,10.6).s().p("AEnEWIgLgFQgXh/gqhZQgthfg6g8Qg6g6g6ggQg7gegygMQgxgLgggBQgegBAAABQBZAMBHAjQBFAiA2AxQA2AxAnA4QAmA3AaA1QAZA2AOAsQAQAsAGAbIABACIgVgLQgLgHgMgJIgRgQQgJgKgIgMQgKgOgHgRQgNgfAAgtIgJgWQgJgWgQgjQgRghgaglQgaglghgeQgjgfgpgPQgqgQgyAJIAOABQAOACAbAOQAZANAkAhQAjAhAqA+QArA8AvBiIABAGQgMgWgRgXQgOgXgSgTQgIgSgMgYQgRghgZglQgagmghgfQgigegqgQQgrgPgyAJIAOABQAOADAbANQAaANAjAhQAbAZAfAoQgUgOgWgIQgTgLgUgIQgrgPgyAJIAOABQANADAVAKIgQACIANABQAJABANAGQAVAOAcAZIAJAJQgKAAgMACQgPgIgQgGQgKgEgMgCQgWgOgZgJQgqgPgzAIIAOACQAPACAaANIAKAGIALAGIgGACIAIAAQASANAVASQAjAhArA+QAeArAgA8QgRgYgUgWIgGgHQgNgYgRgZQgbglghgfQgigdgqgQQgWgHgYgCIAGgDIARgGIAAAAIABAAIASgEQgYADgVAEIgNADIAAgOIAGgBIAHgCIAEgBIAJgCIgNACIgNACIAAg1IANgEIATgFIAXgGQgWAAgUABIgNABIAAgOIAJgCIgJAAIAAiYIAAAAIAEAAIACAAIADAAIAEAAQBiADBKAUQBQAXA4AfQA4AgAlAgQAjAfARAWIARAWQAsBIAbBLQAbBLANBIIAJAxIgHgCg");
	this.shape_8.setTransform(167.8,30.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AneJLQghhAABgsIAAAAIAAgOIACAOQAFAhAPAiQAIATALAQQAYAlAjAYIAUAAIAHAKIgKAKIgEAEQgvgLgihEgAH+kAQgIgHgGgJQgLgQgJgUQgGgOgDgOIAPALIAAAAIAYAvIAAAFIAEAOIABAFIgBgCgAjQm2QADgTAGgQQAUg5AggnIAKgLIAUgQQAZgSAegQQAhgSAqgRIgSALIghAWIgNAJQgWAQgYAWQgkAYgWAdQgKAPgHANQgMAXgGAVQgJAkgBAXIAAASIgNAVQgCgpAHgjgAj2npQATg4AigoIAOgQQAVgWAXgRIgTAQQgLAKgIALQgWAZgOAcQgUAogIAjIgHAkQgIAXgDAPIgCAUIgEAKQgBhDAQgzgAAWplIANgDQAVgFAYgCIgSAEIgBAAIAAAAIgRAGIgGADIAAAAQgOgBgOABIAMgDg");
	this.shape_9.setTransform(135.4,89);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#BDBDBD","#E0E0E0","#D7D7D7"],[0,0.969,1],10.6,-38.3,-49.1,-38.8).s().p("AkpLrIgBAAQgJgQgJgdQgPgvAAgeIAEguIAAgCIAAgBQASAdAUAbQAcAmAeAgIAAAAIgDAMIgBADIgBgRQgeAXgbAZIgEgBgAG4K3QAagcAYghIABACIABAHQAAAPgTBCIghgdgAnbgPIgBgBIgBAAIgLgFIgCggQgBgcACguIAAgKQACggAFgkIAIg0QALhDAahIQAZhJAshFIARgWQAQgVAjgeQAjgeA4gfQA4gfBOgVIAFgBQBHgTBcgDIAACXQhNgCg1AUQg5AUgkAjQgjAjgUAnIgBADQgTAmgIAiQgHAkgCAWIgBAYQgNBCgTAtQgTAugSAcIgFAHIAKgJQAegaAWgeIASgZQgNAWgPASQgmAugtAcQgcARgZAMIgTAIIgQAGIgcAJIgeAJgAhppHQg5AVgkAiQgkAjgTAnQgUAogIAjIgBAHQgHAfgBAUIgBAYQgOBCgSAtQgTAugTAcIgEAHIAKgIQAegbAWgeQAWgeAMgVIAMgWQgFhOATg5QAIgWAKgTQAOgfAUgYQAignAmgZQAngaAigNQAjgOAVgFIAYgFIgVAAQhEAAgyASgAigppQg5AVgjAiQglAjgTAnQgUAogIAjQgIAkgBAWIgBAYIgMAzIgHAYIgEALIgJAaQgPAjgOAZIgJAOIgEAGIAKgIIAFgEQAagZAVgbQAWgfAMgUIAMgXQgCgiADgfQADgmALgfQASg5AhgoQAignAmgZQAngZAigOQAkgNAVgGIAYgFIgSAAQhHAAgzASgAgjqxQgcABgtAMQguAKg2AfQg2Afg0A7Qg1A7grBgQgaA8gTBOQALgqAVg0QAVg1Aig3QAig4AygxQAygwBFgjQBEgiBagNIgHAAIgVAAg");
	this.shape_10.setTransform(128.3,77.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CCCCCC").s().p("AgVZnIgCgFIAAAAIgSgtQgWg5gmhkQglhlgtiGQgsiGgtidQgticglioQgYhogRhpIATANIATAMQAoAdAfAgQAlAmAYAhQAYAiALAVIAKATIgFgMQAYAzAbAvQAwBQA4A/IAZgZQAYgbApg+QAng3AthbIgSAoIALgTQAMgVAZgjQAZgiAngnQAngnA2glIAegSIAHgFIgBAJQgPBzgYCDQgXCCgfCIQggCIgqCGQgrCHg2B8QgzB2g/BlIgHALgACMY2QAhgsA5hSQA4hRBHhwQBIhxBOiJQBNiKBLicQBMicA/ipIAPAGIgTAvQgTAugiBQQgiBQgxBoQgxBng9B0Qg8BzhGB2QhGB0hPBrQhPBshUBWIAigsgAiHZaQhThWhNhqQhOhrhGh1QhGh1g8hzQg8hzgwhoQgwhngjhQQgihRgSgtIgSgvIANgHQBBCpBLCdQBKCcBOCJQBNCKBHBwQBHBwA3BRQA4BSAhAsIAfAqIACACIgCgCgANlYPIgOgsQgNgtgPhVQgPhVgFh2IAAg1IAAgBIAKixIAAgHIACgWQASiQAxiiQAxigBcitIgVAtQgXAyghBZQggBaggB5QgfB5gSCPQgRCPAICdQAJCaAsCgIABAEIgMACgAubXgQAuihAIiYQAIiXgRiIQgSiHgghxQgghwghhSQgSgtgPghQA8B8AlB0QAyCeARCIQARCIgEBuQgFBugOBOQgPBNgNAqQgOApgBABgAMtGYgAJxEmQAQgBAQAAICcBzgAquElQAPAAAPABIiyBtgAKcDbIBZg9IhKBKIgPgNgAsKCYIBSA5IgOAMgAF4i/QAJgQAEgUQAEgWAAgrQABgOgEgPQAPgVAOgXIAHgNQAJAeABAbQAAAwgSAmQgMAbgXAYIgHgHgAnDjCQgnghgZg1QgXgyAAgpQAAgKAFgNIALgYQAEgKAcgKIADgCQAOAeAQAcIgEALQgDAPAAAuIALBNQAEAXAGAQgAH7pAIAKABIABABQABAAgBAFIAAABQAAAIgOAJIgFADIAIgcgAIOqWQAIgTAHgUQALgfAEgVIAGgWQATg2ACgjIAAgCQAFAXAAAUQAAAigIAjIgUBHQgPA1gjAxIgCACQAKgpAIgqgAoqqXIABAAIAAAAIgBAAgApBrFQgYgxgIgZIgCgFIgCgEQgRhCAAhGQAAg4AQg3IAIgFIABgRQgCAuABAcIACAgIALAFIgBABIgHACIgaAEIAFAAIAEAAIAXAAQgGAWAAAbQAAAdACAbIAFAtIAEATQAHAsAPAYIAKANIABAHQgKgJgKgOgAJMuYIADgCIABgSQAFAdABAbQgEgSgGgSgAJTvAIAAgFIgDAAIgFgBIgSgFQgPgFgLgGIgLgGIgGgEIgEgDQgYgSgNgVIgDgFIgOgIIgCAAQgQgHgNgIIgDgCIgPgLQgSgQgKgRQgQgZgFgSIgFgTIgLgZIADAIIAIAXQABAtAOAgQAHASALAPIAFAGIAKANQAUAUAVAMQAUAMANAFIAMAEIACAAIgCAAQg0gGgegUQgGgDgEgEQgOgDgMgEIgGgCQgMgFgKgGIgGgDQgfgVgQgZQgPgZgFgTIgFgTIgbg4Qggg8gegrQgrg+gjghQgVgTgSgNIgIAAIAGgCIgLgGIgKgGQgagNgPgCIgNgCQAygJAqAPQAZAKAWAOQAMACAKAEQAQAGAPAIQAMgCAKAAIgJgJQgcgagVgOQgNgFgJgBIgNgBIAQgDQgVgKgNgCIgOgBQAygJArAPQAUAHATAMQAWAIAUAOQgfgpgbgYQgjghgagNQgbgOgOgCIgOgBQAygJArAPQAqAQAiAeQAiAfAaAlQAZAmARAiQAMAYAIASQASATAOAWQARAXAMAWIgBgFQgvhigrg+Qgqg9gkghQgkghgZgOQgbgNgOgCIgOgBQAygJAqAPQAqAPAjAfQAhAfAaAlQAaAlARAiQAQAiAJAWIAJAXQAAAtANAfQAHARAKAOQAIAMAJAKIARAQQAMAJALAHIAVALIgBgCQgGgbgQgsQgOgsgZg2Qgag2gmg3Qgng4g2gxQg2gxhGgiQhHgjhZgMQAAgBAeABQAgABAxALQAyAMA8AeQA6AfA6A7QA6A8AtBgQAqBZAXB/IALAEIAHADIAGACIgGAAIgSgEIACAQIgCgQQgPgDgLgEQgTgGgPgKIgKgHQgOgKgKgMIADAJIAJAXIAAAAIABAJIAEADIAWAKIAKADIADABIgDAAIgbgEIgJgDIACAQQAEAXAHASIAHAOIAIAOIABAAIAHACIADACIgDgBIgDAAIADACQALAGAJADIAFABIAJADIgIgBQgNgBgMgDIAAAAIAKALIAMAMQAJAIAIAGIAEACIAHAEIAPAJIAIAEIACABIgCgGIAAgfIADABIAJAoIAMAEIgLgCIADAOQADAIAAAFIgBAEIgHADQgJgGABgZgAEfzAIAJAWQAAAtAOAfQAOAgAUAUQATAUATAMIABABIAEACIAEACIgEgDIgDgEQgIgJgGgJQgQgZgFgSQgEgSABgCQgmhPgkg3IAPAjgAGvxmQAJAUALAQQAGAJAIAHIABACIgBgFIgEgOIAAgFIgYgvIAAAAIgPgLQADAOAGAOgAGOx8IgCgHIgDgHIAFAOgADe1sIAIAGQAVATASAWQgQgWgOgRIgSgWQgUgIgKgCIgEAAQATAKAQAOgAJovBIABAAIgBAAgAGCvNIAAAAIAAAAgAFpvRIgPgEQgagHgSgMQgggVgPgZQgQgZgEgSIgFgTQgvhigqg+Qgrg9gkgiQgggdgYgNIgFgEIgXgKIAAAAIgCgBIgKAFQggARggAhQgfAigXA3QgWA3gDBTIADAOQACAOgHAXQgFAWgYAaQgWAagyAXIgTAIIAOgKQAZgUAUgmIgCABQgXAagxAYIgUAJIAPgLQAegZAUguQAVgvADhMIAAgGIAAgSQABgXAJgkQAGgVAMgXQAHgNAKgPQAWgdAkgYIASgMQApgXA9gKIANgBIAMgCIgIACIgEABIgHABIgGACQgTAGgbAPQgaAOgZAYQANgKAQgJQAUgLAZgJIgIAAIATgDQAOgBAOABIAAAAQAXABAWAIQAqAPAiAfQAhAfAbAkQARAaANAYIALAWQASAiAIAWIAJAXQAAAsAOAgQANAfAVAVQAUAVATAMIAMAGIANAGIAJAEIAOAFIgZgEgAlqwAIAAgCQAMgRAMgZIAOggQASgtAOhCQgBAAACgXIACgXIAHgkQAIgjAUgoQAOgcAWgZQAIgLALgKIATgQQgXARgVAWIgOAQQgiAogTA4QgQAzABBDIABARIgMAWIgQAaIgSAZQgWAegdAaIgLAJIAFgHQASgcATguQATgtANhCIABgYQACgWAIgkQAHgiAUgmIABgDQATgnAjgjQAlgjA4gUQA2gUBNACIAJAAIgJACIgOADQgWAFgjAOQggAMgjAXQAYgPAegLQAlgNAvgDIANgBQATgBAWAAIgXAFIgSAGIgNAEIgZAJQgiAOgmAZIgLAIQgbATgZAbIgKALQggAngUA5QgGAQgDATQgHAjACApIAAAXIgMAWQgMAWgXAdQgVAegeAbIgJAIIADgFgAIov9IABAAIgBAAgAndwWQAUgcASguQASgtAOhCIABgYQACgUAGgfIABgHQAJgjATgoQAUgnAjgjQAlgiA4gVQA5gVBTADIgXAFQgWAFgkAOQgiANgnAaQgmAZgiAnQgTAYgPAfQgKATgIAWQgSA5AEBOIgMAWQgMAVgWAeQgWAegeAbIgJAIIADgHgAoUw3IAJgOQAPgZAOgjIAJgaIAEgLIAIgYIALgzIABgYQACgWAHgkQAJgjATgoQAUgnAkgjQAjgiA6gVQA5gUBSACIgXAFQgWAGgkANQgiAOgnAZQgmAZgiAnQggAogTA5QgKAfgEAmQgDAfACAiIgMAXQgMAUgWAfQgUAbgbAZIgFAEIgJAIIADgGgAoO0sQArhgA1g7QA0g7A2gfQA3gfAtgKQAtgMAcgBIAdAAQhbANhEAiQhEAjgyAwQgzAxghA4QgjA3gVA1QgVA0gLAqQAThOAag8g");
	this.shape_11.setTransform(139.9,170.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#BFBFBF").s().p("Am5K6QgwgVgjhGQgfg/AAgyQAAgwALgbQAQgoApgRIAFgCIANAfIgDABQgcAKgEAKIgLAZQgFAMAAAKQAAApAXAyQAZA1AnAhIAIAAQgGgPgEgXIgLhOQAAguADgPIAEgLIAKARIAFAIIgBABIAAACIgDAuQAAAeAOAvQAJAdAJAQIABAAIAEACIgTATIgHgKIgUAAQgjgYgYglQgLgQgIgSQgPgigFgiIgCgNIAAANIAAAAQgBAsAhBAQAiBEAvALIgQATgAGiKXIgRgRQAXgYAMgbQASgmAAgwQgBgbgJgeIAPgbIAGANIAHAFIgBAIIgBACIgBABQACAQABAoQgBAmgRA6QgNAngSAVIAAADIgFgGgAF4JtQAShCAAgPIAAgHIgBgCIABgCIAOgUQAEAPgBAOQAAArgEAWQgEAUgJAQIgSgSgAIFEaIAFgDIgGAHIABgEgAIYEFQABgFgBAAIgBgBIgKgBIABgDIACgCQAjgxAPg0IAUhIQAIgiAAgjQAAgTgFgXQACgfgFgTIgJADQgSAFgRABIgQgBIgFgBQglgIgggYIgDgBQgigagdghIgFgGIgHgIIgJgLIgGgIQAKAFAMAFIAGACQAMAEAOADQAEAEAGADQAeAUA0AGIACABIgCgBIgMgEQgNgFgUgMQgVgLgUgVIgKgMIgFgHQgLgPgHgSQgOgggBgtIgIgWIgDgIIALAYIAFATQAFATAQAZQAKAQASAQIAPALIADACQANAIAQAHIACAAIAOAIIADAGQANAUAYASIAEADIAGAEIALAGQALAHAPAEIASAFIAFABIADAAIAAAFQgBAZAJAGIAHgDIABgDQAEAcAAAcIABAmQgCAagJAAIAAAAQgCBKgYBCQgWA6gnAwgAJhhbIgDACQAGATAEARQgBgbgFgcIgBARgAo6CbIgGgNQgJgLgJgRQgWgtgDgkIgBgOQgJghgCgOQgBgKgBg7QAAhCABgGQACgMAKgaQAHgiALgaQAIgSAOgXQgFAkgCAgIAAAKIgBASIgIAEQgQA3AAA5QAABFARBBIACAEIACAGQAIAYAYAxQAKAOAKAKIAEAWIgBAAIAAABIABgBIAJAwQgQgEgcg4gApchvIgFAAIAagFIAHgCIAEAAIAAAAIAegJIAcgJIARgGIASgIQAagMAbgRQAtgcAmguQAPgSANgVIAQgaIAMgXIgBgRIAEgKIACgUQADgPAIgXIgCAXQgCAXABAAQgOBCgSAtIgOAhQgMAYgMASIAAABIgLAJIgCACIgDABIgtAcIgTAIIAAABIgjANIgPAEIgVAGQgWAEgaADIgMABIgWABIgXABIgEAAgAJiiKIgIgFIgPgJIgHgEIgEgCQgIgGgJgIIgMgMIgKgKIAAgBQAMADANABIAIABIABAAIgBAAIgJgCIgFgCQgJgDgLgGIgDgBIADAAIADAAIgDgCIgHgCIgBAAIgIgOIgHgOQgHgSgEgWIgCgQIAJACIAbAEIADABIgDgCIgKgDIgWgKIgEgCIgBgJIAAgBIgJgXIgDgJQAKAMAOALIAKAGQAPAKASAGQAMAFAPADIACAQIgCgQIASADQAGAoADAjIABAdIAEAKIgDgBIAAAgIACAFIgCAAgAGVjIIgEgBIgBgBQgTgMgTgVQgUgUgOggQgOgfAAgtIgJgWIgPgjQAkA3AmBQQgBABAEASQAFATAQAYQAGAJAIAJIADAEIAEADIgEgCgAD4onIgIgGQgQgOgTgKIAEAAQAKACAUAJIASAVQAOARAQAXQgSgWgVgUgAgQpIIAKgEIACAAIgOAJQgZAPglAfQAggiAggRgAgypRQAbgOATgHIAAAOIgMADIgTADIAIAAQgZAJgUAMQgQAIgNALQAZgZAagOgAhwplIALgIQAmgZAigNIAZgKIAAA1Qg9AKgpAWIgSAMQAYgVAWgQIANgJIAhgXIATgKQgrAQghATQgeAQgZARIgVAQQAagbAbgTgAhLqjQAjgOAWgFIAOgCIAAAOQgvADglANQgeALgYAPQAjgXAggMg");
	this.shape_12.setTransform(138.1,87.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#FFFFFF","#AEACAB"],[0.737,1],0,6,0,-5.8).s().p("AAFgCQAJgWgEgNQgDgMgHgFIgHgEIAAAAQAXgBACARQACARgIAYQgKAXgJATIgGALIAAAAIAAABIgFAHg");
	this.shape_13.setTransform(130.3,89.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#FFFFFF","#AEACAB"],[0.737,1],-5.9,0,5.7,0).s().p("Ag5AKQABgGAGgFQAHgGAPgEIAPgBIAFAAIABAAIAbgDIAoAAIgSAAQgRAAgXADIgCABQgUACgRAHQgJACgGAFQgFAFgBAGQgBAAACgGg");
	this.shape_14.setTransform(94.1,81.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#AEACAB").s().p("AhiBXIgFgEIAIgPQAHgOAIgUQAHgRADgRIAAgBIABgEIAAgBIABgIIAAgBQAAgPgFgJIgTgLIgBAAIAAADIgcgEIgKgBIgDgBIg3gGIgEAAIgbgDIgQgBIgqgEQgwgCgqAAQgrAAgbAHQgbAGgBAPIgEBOIAAAHIgFgCQgGgCgGgIQgGgHgFgPIgDgDIgJgFQgFgDgBgCIABgNIgCgEIgBgKIAAgHIAAgJIgJgdIARAAIATABIAGgFQgBgBAPgDIACAAIANgDIABAAIApgCQAqgBBOAFQAeACAjAFQA9AGBNALIAAgCIABAAIABgGIAVACQAWACAmABQAlAAAzgFIABAHIAAABQB+gSBOgGQBPgGApABQApABAPAEIAPADQAHAFADAHIACAHIAGAKIAegOIADABIgGA2IgOAEIAAADIgGAFQgEADgFACIgEADQgGAWgLAHQgKAGAAgBIAAgDIgEhSQgCgPgbgGQgbgGgqAAQgsgBgvADIghADQgdACgdAEQgqAEgbAEIgGABIgVADIAAgEIgSAKQgFALABAQIAAgDIAAADIAAADIAAABIAAABIAAABIAAABIABACIAAADQAEAQAHASIAOAjIAHAOIgCAEQgGAFgGgEQgJgFgGgMQgHgLgGgLIgDgLQgNgVgNgIQgMgHgHgBIgCAAIgDAAIgCAAIgDAAQgJABgNAIQgMAIgOAUIgFAMIgLAWQgHANgIAFIgBAAIgEABQgDAAgDgDgAhMgrQAHAFADAMQAEANgIAVIgYA/IAFgHIAAgBIAAAAIAGgLQAKgTAKgYQAIgXgCgRQgCgRgYABIgBAAIAIAEgAnEhUIgOABQgPAEgHAGQgHAGAAAGQgDAGABAAQACgGAFgFQAFgFAKgDQAQgHAVgCIADgBQAXgDARAAIASAAIgoAAIgdADIAAAAIgGAAg");
	this.shape_15.setTransform(137.9,88.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#545355").s().p("AkVBhIgTgDIgtgIQgbgGgcgIQgbgJgTgLQgUgLgBgOIgCgRIAAgCIAEhOQABgPAbgGQAbgHArAAQAqAAAwACIAqAEIg2gDIhMAAIgdAAQgkAAgPAGQgNAHgCAGIgBAHQgCAUAAAWIACAkIADAQQABAOASALQATAKAbAIQAaAIAaAGIAsAHIATADQA5AGAkgFQAjgFATgJQARgJAHgIIAFgIIAFAEIgGAHQgGAIgUAKQgSAJglAFQgRADgXAAQgZAAgggDgAC1BhQgkgFgUgJQgTgKgGgIIgFgIIACgEIgHgOIgOgjQgHgRgEgRIAFAMIAcBHQAAABAGAIQAHAIARAJQATAJAjAFQAkAEA6gFIATgDIArgIQAagFAbgJQAagHATgLQASgLACgOIABgQQACgOAAgWQABgVgDgVQACAAgCgHQgCgGgPgHQgNgGgjAAIgfAAIhLABIguACIAhgDQAvgDAsABQAqAAAbAGQAbAGACAPIAEBSIgCAPQgDAOgSALQgTALgcAJQgaAIgcAGQgcAGgSACIgTADQggADgaAAQgVAAgRgCgABAgtIAAADQgBgQAFgLIASgKIAAAEIAVgDIgUAEIgIAEQgJAEgFAMIAAAAIAAACIAAAAIgBACIAAAIIAAgDg");
	this.shape_16.setTransform(137.4,91.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.per5, new cjs.Rectangle(4.8,2.5,270,332.9), null);


(lib.jafoafwoawf = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(1));

	// Layer 1
	this.instance = new lib.per5();
	this.instance.parent = this;
	this.instance.setTransform(98.4,121.7,0.15,0.15,0,0,0,137.7,167);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:137.6,regY:166.8,scaleX:0.74,scaleY:0.74,x:98.5},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(78.4,97,40.5,50);


// stage content:
(lib.People_icon_three_Canvas = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.jafoafwoawf();
	this.instance.parent = this;
	this.instance.setTransform(200,200.1,1,1,0,0,0,100,123.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(713.4,498.7,40.5,50);
// library properties:
lib.properties = {
	width: 1070,
	height: 650,
	fps: 24,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;